# -------- ENGLISH --------
# Logistic Regression - named entities features
python3 src/util/extract.py src/english/named_entities/logisticregression/results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: entidades nomeadas + regressão logística" Blues

# Naive Bayes - named entities features
python3 src/util/extract.py src/english/named_entities/naivebayes/BernoulliNB_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: entidades nomeadas + classificador bayesiano (Bernoulli)" Blues
python3 src/util/extract.py src/english/named_entities/naivebayes/GaussianNB_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: entidades nomeadas + classificador bayesiano (Gaussian)" Blues
python3 src/util/extract.py src/english/named_entities/naivebayes/MultinomialNB_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: entidades nomeadas + classificador bayesiano (Multinomial)" Blues
# END BLOCK

# Logistic Regression - ngrams features
python3 src/util/extract.py src/english/ngrams/logisticregression/unigrams_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + regressão logística" Blues
python3 src/util/extract.py src/english/ngrams/logisticregression/bigrams_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: bigramas + regressão logística" Blues
python3 src/util/extract.py src/english/ngrams/logisticregression/trigrams_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: trigramas + regressão logística" Blues

# Naive Bayes - ngrams features
python3 src/util/extract.py src/english/ngrams/naivebayes/BernoulliNB_unigrams_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + classificador bayesiano (Bernoulli)" Blues
python3 src/util/extract.py src/english/ngrams/naivebayes/BernoulliNB_bigrams_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: bigramas + classificador bayesiano (Bernoulli)" Blues
python3 src/util/extract.py src/english/ngrams/naivebayes/BernoulliNB_trigrams_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: trigramas + classificador bayesiano (Bernoulli)" Blues

python3 src/util/extract.py src/english/ngrams/naivebayes/GaussianNB_unigrams_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + classificador bayesiano (Gaussian)" Blues
python3 src/util/extract.py src/english/ngrams/naivebayes/GaussianNB_bigrams_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: bigramas + classificador bayesiano (Gaussian)" Blues
python3 src/util/extract.py src/english/ngrams/naivebayes/GaussianNB_trigrams_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: trigramas + classificador bayesiano (Gaussian)" Blues

python3 src/util/extract.py src/english/ngrams/naivebayes/MultinomialNB_unigrams_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + classificador bayesiano (Multinomial)" Blues
python3 src/util/extract.py src/english/ngrams/naivebayes/MultinomialNB_bigrams_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: bigramas + classificador bayesiano (Multinomial)" Blues
python3 src/util/extract.py src/english/ngrams/naivebayes/MultinomialNB_trigrams_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: trigramas + classificador bayesiano (Multinomial)" Blues
# END BLOCK

# Perceptron - vectors features with sum
python3 src/util/extract.py src/english/vectors/sum/neuralnetwork/w2v_size25_window1_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=25, window=1) + perceptron multicamadas" Blues
python3 src/util/extract.py src/english/vectors/sum/neuralnetwork/w2v_size25_window2_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=25, window=2) + perceptron multicamadas" Blues
python3 src/util/extract.py src/english/vectors/sum/neuralnetwork/w2v_size25_window3_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=25, window=3) + perceptron multicamadas" Blues
python3 src/util/extract.py src/english/vectors/sum/neuralnetwork/w2v_size25_window4_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=25, window=4) + perceptron multicamadas" Blues
python3 src/util/extract.py src/english/vectors/sum/neuralnetwork/w2v_size25_window5_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=25, window=5) + perceptron multicamadas" Blues
python3 src/util/extract.py src/english/vectors/sum/neuralnetwork/w2v_size50_window1_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=50, window=1) + perceptron multicamadas" Blues
python3 src/util/extract.py src/english/vectors/sum/neuralnetwork/w2v_size50_window2_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=50, window=2) + perceptron multicamadas" Blues
python3 src/util/extract.py src/english/vectors/sum/neuralnetwork/w2v_size50_window3_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=50, window=3) + perceptron multicamadas" Blues
python3 src/util/extract.py src/english/vectors/sum/neuralnetwork/w2v_size50_window4_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=50, window=4) + perceptron multicamadas" Blues
python3 src/util/extract.py src/english/vectors/sum/neuralnetwork/w2v_size50_window5_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=50, window=5) + perceptron multicamadas" Blues
python3 src/util/extract.py src/english/vectors/sum/neuralnetwork/w2v_size100_window1_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=100, window=1) + perceptron multicamadas" Blues
python3 src/util/extract.py src/english/vectors/sum/neuralnetwork/w2v_size100_window2_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=100, window=2) + perceptron multicamadas" Blues
python3 src/util/extract.py src/english/vectors/sum/neuralnetwork/w2v_size100_window3_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=100, window=3) + perceptron multicamadas" Blues
python3 src/util/extract.py src/english/vectors/sum/neuralnetwork/w2v_size100_window4_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=100, window=4) + perceptron multicamadas" Blues
python3 src/util/extract.py src/english/vectors/sum/neuralnetwork/w2v_size100_window5_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=100, window=5) + perceptron multicamadas" Blues

# Support Vector Machine - vectors features with sum
python3 src/util/extract.py src/english/vectors/sum/svm/w2v_size25_window1_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=25, window=1) + SVM" Blues
python3 src/util/extract.py src/english/vectors/sum/svm/w2v_size25_window2_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=25, window=2) + SVM" Blues
python3 src/util/extract.py src/english/vectors/sum/svm/w2v_size25_window3_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=25, window=3) + SVM" Blues
python3 src/util/extract.py src/english/vectors/sum/svm/w2v_size25_window4_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=25, window=4) + SVM" Blues
python3 src/util/extract.py src/english/vectors/sum/svm/w2v_size25_window5_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=25, window=5) + SVM" Blues
python3 src/util/extract.py src/english/vectors/sum/svm/w2v_size50_window1_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=50, window=1) + SVM" Blues
python3 src/util/extract.py src/english/vectors/sum/svm/w2v_size50_window2_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=50, window=2) + SVM" Blues
python3 src/util/extract.py src/english/vectors/sum/svm/w2v_size50_window3_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=50, window=3) + SVM" Blues
python3 src/util/extract.py src/english/vectors/sum/svm/w2v_size50_window4_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=50, window=4) + SVM" Blues
python3 src/util/extract.py src/english/vectors/sum/svm/w2v_size50_window5_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=50, window=5) + SVM" Blues
python3 src/util/extract.py src/english/vectors/sum/svm/w2v_size100_window1_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=100, window=1) + SVM" Blues
python3 src/util/extract.py src/english/vectors/sum/svm/w2v_size100_window2_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=100, window=2) + SVM" Blues
python3 src/util/extract.py src/english/vectors/sum/svm/w2v_size100_window3_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=100, window=3) + SVM" Blues
python3 src/util/extract.py src/english/vectors/sum/svm/w2v_size100_window4_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=100, window=4) + SVM" Blues
python3 src/util/extract.py src/english/vectors/sum/svm/w2v_size100_window5_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=100, window=5) + SVM" Blues

# Perceptron - vectors features with pad
python3 src/util/extract.py src/english/vectors/pad/neuralnetwork/w2v_size25_window1_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=25, window=1) + perceptron multicamadas" Blues
python3 src/util/extract.py src/english/vectors/pad/neuralnetwork/w2v_size25_window2_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=25, window=2) + perceptron multicamadas" Blues
python3 src/util/extract.py src/english/vectors/pad/neuralnetwork/w2v_size25_window3_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=25, window=3) + perceptron multicamadas" Blues
python3 src/util/extract.py src/english/vectors/pad/neuralnetwork/w2v_size25_window4_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=25, window=4) + perceptron multicamadas" Blues
python3 src/util/extract.py src/english/vectors/pad/neuralnetwork/w2v_size25_window5_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=25, window=5) + perceptron multicamadas" Blues
python3 src/util/extract.py src/english/vectors/pad/neuralnetwork/w2v_size50_window1_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=50, window=1) + perceptron multicamadas" Blues
python3 src/util/extract.py src/english/vectors/pad/neuralnetwork/w2v_size50_window2_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=50, window=2) + perceptron multicamadas" Blues
python3 src/util/extract.py src/english/vectors/pad/neuralnetwork/w2v_size50_window3_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=50, window=3) + perceptron multicamadas" Blues
python3 src/util/extract.py src/english/vectors/pad/neuralnetwork/w2v_size50_window4_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=50, window=4) + perceptron multicamadas" Blues
python3 src/util/extract.py src/english/vectors/pad/neuralnetwork/w2v_size50_window5_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=50, window=5) + perceptron multicamadas" Blues
python3 src/util/extract.py src/english/vectors/pad/neuralnetwork/w2v_size100_window1_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=100, window=1) + perceptron multicamadas" Blues
python3 src/util/extract.py src/english/vectors/pad/neuralnetwork/w2v_size100_window2_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=100, window=2) + perceptron multicamadas" Blues
python3 src/util/extract.py src/english/vectors/pad/neuralnetwork/w2v_size100_window3_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=100, window=3) + perceptron multicamadas" Blues
python3 src/util/extract.py src/english/vectors/pad/neuralnetwork/w2v_size100_window4_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=100, window=4) + perceptron multicamadas" Blues
python3 src/util/extract.py src/english/vectors/pad/neuralnetwork/w2v_size100_window5_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=100, window=5) + perceptron multicamadas" Blues

# Support Vector Machine - vectors features with pad
python3 src/util/extract.py src/english/vectors/pad/svm/w2v_size25_window1_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=25, window=1) + SVM" Blues
python3 src/util/extract.py src/english/vectors/pad/svm/w2v_size25_window2_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=25, window=2) + SVM" Blues
python3 src/util/extract.py src/english/vectors/pad/svm/w2v_size25_window3_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=25, window=3) + SVM" Blues
python3 src/util/extract.py src/english/vectors/pad/svm/w2v_size25_window4_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=25, window=4) + SVM" Blues
python3 src/util/extract.py src/english/vectors/pad/svm/w2v_size25_window5_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=25, window=5) + SVM" Blues
python3 src/util/extract.py src/english/vectors/pad/svm/w2v_size50_window1_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=50, window=1) + SVM" Blues
python3 src/util/extract.py src/english/vectors/pad/svm/w2v_size50_window2_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=50, window=2) + SVM" Blues
python3 src/util/extract.py src/english/vectors/pad/svm/w2v_size50_window3_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=50, window=3) + SVM" Blues
python3 src/util/extract.py src/english/vectors/pad/svm/w2v_size50_window4_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=50, window=4) + SVM" Blues
python3 src/util/extract.py src/english/vectors/pad/svm/w2v_size50_window5_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=50, window=5) + SVM" Blues
python3 src/util/extract.py src/english/vectors/pad/svm/w2v_size100_window1_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=100, window=1) + SVM" Blues
python3 src/util/extract.py src/english/vectors/pad/svm/w2v_size100_window2_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=100, window=2) + SVM" Blues
python3 src/util/extract.py src/english/vectors/pad/svm/w2v_size100_window3_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=100, window=3) + SVM" Blues
python3 src/util/extract.py src/english/vectors/pad/svm/w2v_size100_window4_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=100, window=4) + SVM" Blues
python3 src/util/extract.py src/english/vectors/pad/svm/w2v_size100_window5_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" "Corpus em inglês: unigramas + Word2Vec (size=100, window=5) + SVM" Blues
# END BLOCK
# END ENGLISH


# -------- PORTUGUESE --------
# Logistic Regression - ngrams features
python3 src/util/extract.py src/portuguese/ngrams/logisticregression/unigrams_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" "Corpus em português: unigramas + regressão logística" Reds
python3 src/util/extract.py src/portuguese/ngrams/logisticregression/bigrams_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" "Corpus em português: bigramas + regressão logística" Reds
python3 src/util/extract.py src/portuguese/ngrams/logisticregression/trigrams_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" "Corpus em português: trigramas + regressão logística" Reds

# Naive Bayes - ngrams features
python3 src/util/extract.py src/portuguese/ngrams/naivebayes/BernoulliNB_unigrams_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" "Corpus em português: unigramas + classificador bayesiano (Bernoulli)" Reds
python3 src/util/extract.py src/portuguese/ngrams/naivebayes/BernoulliNB_bigrams_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" "Corpus em português: bigramas + classificador bayesiano (Bernoulli)" Reds
python3 src/util/extract.py src/portuguese/ngrams/naivebayes/BernoulliNB_trigrams_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" "Corpus em português: trigramas + classificador bayesiano (Bernoulli)" Reds

python3 src/util/extract.py src/portuguese/ngrams/naivebayes/GaussianNB_unigrams_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" "Corpus em português: unigramas + classificador bayesiano (Gaussian)" Reds
python3 src/util/extract.py src/portuguese/ngrams/naivebayes/GaussianNB_bigrams_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" "Corpus em português: bigramas + classificador bayesiano (Gaussian)" Reds
python3 src/util/extract.py src/portuguese/ngrams/naivebayes/GaussianNB_trigrams_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" "Corpus em português: trigramas + classificador bayesiano (Gaussian)" Reds

python3 src/util/extract.py src/portuguese/ngrams/naivebayes/MultinomialNB_unigrams_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" "Corpus em português: unigramas + classificador bayesiano (Multinomial)" Reds
python3 src/util/extract.py src/portuguese/ngrams/naivebayes/MultinomialNB_bigrams_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" "Corpus em português: bigramas + classificador bayesiano (Multinomial)" Reds
python3 src/util/extract.py src/portuguese/ngrams/naivebayes/MultinomialNB_trigrams_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" "Corpus em português: trigramas + classificador bayesiano (Multinomial)" Reds
# END BLOCK

# Perceptron - vectors features with sum
python3 src/util/extract.py src/portuguese/vectors/sum/neuralnetwork/w2v_size25_window1_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" "Corpus em português: unigramas + Word2Vec (size=25, window=1) + perceptron multicamadas" Reds
python3 src/util/extract.py src/portuguese/vectors/sum/neuralnetwork/w2v_size25_window2_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" "Corpus em português: unigramas + Word2Vec (size=25, window=2) + perceptron multicamadas" Reds
python3 src/util/extract.py src/portuguese/vectors/sum/neuralnetwork/w2v_size25_window3_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" "Corpus em português: unigramas + Word2Vec (size=25, window=3) + perceptron multicamadas" Reds
python3 src/util/extract.py src/portuguese/vectors/sum/neuralnetwork/w2v_size25_window4_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" "Corpus em português: unigramas + Word2Vec (size=25, window=4) + perceptron multicamadas" Reds
python3 src/util/extract.py src/portuguese/vectors/sum/neuralnetwork/w2v_size25_window5_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" "Corpus em português: unigramas + Word2Vec (size=25, window=5) + perceptron multicamadas" Reds
python3 src/util/extract.py src/portuguese/vectors/sum/neuralnetwork/w2v_size50_window1_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" "Corpus em português: unigramas + Word2Vec (size=50, window=1) + perceptron multicamadas" Reds
python3 src/util/extract.py src/portuguese/vectors/sum/neuralnetwork/w2v_size50_window2_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" "Corpus em português: unigramas + Word2Vec (size=50, window=2) + perceptron multicamadas" Reds
python3 src/util/extract.py src/portuguese/vectors/sum/neuralnetwork/w2v_size50_window3_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" "Corpus em português: unigramas + Word2Vec (size=50, window=3) + perceptron multicamadas" Reds
python3 src/util/extract.py src/portuguese/vectors/sum/neuralnetwork/w2v_size50_window4_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" "Corpus em português: unigramas + Word2Vec (size=50, window=4) + perceptron multicamadas" Reds
python3 src/util/extract.py src/portuguese/vectors/sum/neuralnetwork/w2v_size50_window5_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" "Corpus em português: unigramas + Word2Vec (size=50, window=5) + perceptron multicamadas" Reds
python3 src/util/extract.py src/portuguese/vectors/sum/neuralnetwork/w2v_size100_window1_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" "Corpus em português: unigramas + Word2Vec (size=100, window=1) + perceptron multicamadas" Reds
python3 src/util/extract.py src/portuguese/vectors/sum/neuralnetwork/w2v_size100_window2_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" "Corpus em português: unigramas + Word2Vec (size=100, window=2) + perceptron multicamadas" Reds
python3 src/util/extract.py src/portuguese/vectors/sum/neuralnetwork/w2v_size100_window3_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" "Corpus em português: unigramas + Word2Vec (size=100, window=3) + perceptron multicamadas" Reds
python3 src/util/extract.py src/portuguese/vectors/sum/neuralnetwork/w2v_size100_window4_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" "Corpus em português: unigramas + Word2Vec (size=100, window=4) + perceptron multicamadas" Reds
python3 src/util/extract.py src/portuguese/vectors/sum/neuralnetwork/w2v_size100_window5_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" "Corpus em português: unigramas + Word2Vec (size=100, window=5) + perceptron multicamadas" Reds

# Support Vector Machine - vectors features with sum
python3 src/util/extract.py src/portuguese/vectors/sum/svm/w2v_size25_window1_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" "Corpus em português: unigramas + Word2Vec (size=25, window=1) + SVM" Reds
python3 src/util/extract.py src/portuguese/vectors/sum/svm/w2v_size25_window2_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" "Corpus em português: unigramas + Word2Vec (size=25, window=2) + SVM" Reds
python3 src/util/extract.py src/portuguese/vectors/sum/svm/w2v_size25_window3_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" "Corpus em português: unigramas + Word2Vec (size=25, window=3) + SVM" Reds
python3 src/util/extract.py src/portuguese/vectors/sum/svm/w2v_size25_window4_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" "Corpus em português: unigramas + Word2Vec (size=25, window=4) + SVM" Reds
python3 src/util/extract.py src/portuguese/vectors/sum/svm/w2v_size25_window5_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" "Corpus em português: unigramas + Word2Vec (size=25, window=5) + SVM" Reds
python3 src/util/extract.py src/portuguese/vectors/sum/svm/w2v_size50_window1_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" "Corpus em português: unigramas + Word2Vec (size=50, window=1) + SVM" Reds
python3 src/util/extract.py src/portuguese/vectors/sum/svm/w2v_size50_window2_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" "Corpus em português: unigramas + Word2Vec (size=50, window=2) + SVM" Reds
python3 src/util/extract.py src/portuguese/vectors/sum/svm/w2v_size50_window3_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" "Corpus em português: unigramas + Word2Vec (size=50, window=3) + SVM" Reds
python3 src/util/extract.py src/portuguese/vectors/sum/svm/w2v_size50_window4_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" "Corpus em português: unigramas + Word2Vec (size=50, window=4) + SVM" Reds
python3 src/util/extract.py src/portuguese/vectors/sum/svm/w2v_size50_window5_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" "Corpus em português: unigramas + Word2Vec (size=50, window=5) + SVM" Reds
python3 src/util/extract.py src/portuguese/vectors/sum/svm/w2v_size100_window1_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" "Corpus em português: unigramas + Word2Vec (size=100, window=1) + SVM" Reds
python3 src/util/extract.py src/portuguese/vectors/sum/svm/w2v_size100_window2_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" "Corpus em português: unigramas + Word2Vec (size=100, window=2) + SVM" Reds
python3 src/util/extract.py src/portuguese/vectors/sum/svm/w2v_size100_window3_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" "Corpus em português: unigramas + Word2Vec (size=100, window=3) + SVM" Reds
python3 src/util/extract.py src/portuguese/vectors/sum/svm/w2v_size100_window4_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" "Corpus em português: unigramas + Word2Vec (size=100, window=4) + SVM" Reds
python3 src/util/extract.py src/portuguese/vectors/sum/svm/w2v_size100_window5_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" "Corpus em português: unigramas + Word2Vec (size=100, window=5) + SVM" Reds
# END BLOCK
# END PORTUGUESE
