# -------- ENGLISH --------
# Logistic Regression - named entities features
python3 src/util/extract.py src/english/named_entities/logisticregression/results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" > src/english/named_entities/logisticregression/results_extracted.txt

# Naive Bayes - named entities features
python3 src/util/extract.py src/english/named_entities/naivebayes/BernoulliNB_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" > src/english/named_entities/naivebayes/BernoulliNB_results_extracted.txt
python3 src/util/extract.py src/english/named_entities/naivebayes/GaussianNB_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" > src/english/named_entities/naivebayes/GaussianNB_results_extracted.txt
python3 src/util/extract.py src/english/named_entities/naivebayes/MultinomialNB_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" > src/english/named_entities/naivebayes/MultinomialNB_results_extracted.txt
# END BLOCK

# Logistic Regression - ngrams features
python3 src/util/extract.py src/english/ngrams/logisticregression/unigrams_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" > src/english/ngrams/logisticregression/unigrams_results_extracted.txt
python3 src/util/extract.py src/english/ngrams/logisticregression/bigrams_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" > src/english/ngrams/logisticregression/bigrams_results_extracted.txt
python3 src/util/extract.py src/english/ngrams/logisticregression/trigrams_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" > src/english/ngrams/logisticregression/trigrams_results_extracted.txt

# Naive Bayes - ngrams features
python3 src/util/extract.py src/english/ngrams/naivebayes/BernoulliNB_unigrams_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" > src/english/ngrams/naivebayes/BernoulliNB_unigrams_results_extracted.txt
python3 src/util/extract.py src/english/ngrams/naivebayes/BernoulliNB_bigrams_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" > src/english/ngrams/naivebayes/BernoulliNB_bigrams_results_extracted.txt
python3 src/util/extract.py src/english/ngrams/naivebayes/BernoulliNB_trigrams_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" > src/english/ngrams/naivebayes/BernoulliNB_trigrams_results_extracted.txt

python3 src/util/extract.py src/english/ngrams/naivebayes/GaussianNB_unigrams_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" > src/english/ngrams/naivebayes/GaussianNB_unigrams_results_extracted.txt
python3 src/util/extract.py src/english/ngrams/naivebayes/GaussianNB_bigrams_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" > src/english/ngrams/naivebayes/GaussianNB_bigrams_results_extracted.txt
python3 src/util/extract.py src/english/ngrams/naivebayes/GaussianNB_trigrams_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" > src/english/ngrams/naivebayes/GaussianNB_trigrams_results_extracted.txt

python3 src/util/extract.py src/english/ngrams/naivebayes/MultinomialNB_unigrams_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" > src/english/ngrams/naivebayes/MultinomialNB_unigrams_results_extracted.txt
python3 src/util/extract.py src/english/ngrams/naivebayes/MultinomialNB_bigrams_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" > src/english/ngrams/naivebayes/MultinomialNB_bigrams_results_extracted.txt
python3 src/util/extract.py src/english/ngrams/naivebayes/MultinomialNB_trigrams_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" > src/english/ngrams/naivebayes/MultinomialNB_trigrams_results_extracted.txt
# END BLOCK

# Perceptron - vectors features
python3 src/util/extract.py src/english/vectors/neuralnetwork/w2v_size25_window1_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" > src/english/vectors/neuralnetwork/w2v_size25_window1_results_extracted.txt
python3 src/util/extract.py src/english/vectors/neuralnetwork/w2v_size25_window2_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" > src/english/vectors/neuralnetwork/w2v_size25_window2_results_extracted.txt
python3 src/util/extract.py src/english/vectors/neuralnetwork/w2v_size25_window3_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" > src/english/vectors/neuralnetwork/w2v_size25_window3_results_extracted.txt
python3 src/util/extract.py src/english/vectors/neuralnetwork/w2v_size25_window4_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" > src/english/vectors/neuralnetwork/w2v_size25_window4_results_extracted.txt
python3 src/util/extract.py src/english/vectors/neuralnetwork/w2v_size25_window5_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" > src/english/vectors/neuralnetwork/w2v_size25_window5_results_extracted.txt
python3 src/util/extract.py src/english/vectors/neuralnetwork/w2v_size50_window1_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" > src/english/vectors/neuralnetwork/w2v_size50_window1_results_extracted.txt
python3 src/util/extract.py src/english/vectors/neuralnetwork/w2v_size50_window2_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" > src/english/vectors/neuralnetwork/w2v_size50_window2_results_extracted.txt
python3 src/util/extract.py src/english/vectors/neuralnetwork/w2v_size50_window3_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" > src/english/vectors/neuralnetwork/w2v_size50_window3_results_extracted.txt
python3 src/util/extract.py src/english/vectors/neuralnetwork/w2v_size50_window4_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" > src/english/vectors/neuralnetwork/w2v_size50_window4_results_extracted.txt
python3 src/util/extract.py src/english/vectors/neuralnetwork/w2v_size50_window5_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" > src/english/vectors/neuralnetwork/w2v_size50_window5_results_extracted.txt
python3 src/util/extract.py src/english/vectors/neuralnetwork/w2v_size100_window1_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" > src/english/vectors/neuralnetwork/w2v_size100_window1_results_extracted.txt
python3 src/util/extract.py src/english/vectors/neuralnetwork/w2v_size100_window2_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" > src/english/vectors/neuralnetwork/w2v_size100_window2_results_extracted.txt
python3 src/util/extract.py src/english/vectors/neuralnetwork/w2v_size100_window3_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" > src/english/vectors/neuralnetwork/w2v_size100_window3_results_extracted.txt
python3 src/util/extract.py src/english/vectors/neuralnetwork/w2v_size100_window4_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" > src/english/vectors/neuralnetwork/w2v_size100_window4_results_extracted.txt
python3 src/util/extract.py src/english/vectors/neuralnetwork/w2v_size100_window5_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" > src/english/vectors/neuralnetwork/w2v_size100_window5_results_extracted.txt

# Support Vector Machine - vectors features
python3 src/util/extract.py src/english/vectors/svm/w2v_size25_window1_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" > src/english/vectors/svm/w2v_size25_window1_results_extracted.txt
python3 src/util/extract.py src/english/vectors/svm/w2v_size25_window2_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" > src/english/vectors/svm/w2v_size25_window2_results_extracted.txt
python3 src/util/extract.py src/english/vectors/svm/w2v_size25_window3_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" > src/english/vectors/svm/w2v_size25_window3_results_extracted.txt
python3 src/util/extract.py src/english/vectors/svm/w2v_size25_window4_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" > src/english/vectors/svm/w2v_size25_window4_results_extracted.txt
python3 src/util/extract.py src/english/vectors/svm/w2v_size25_window5_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" > src/english/vectors/svm/w2v_size25_window5_results_extracted.txt
python3 src/util/extract.py src/english/vectors/svm/w2v_size50_window1_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" > src/english/vectors/svm/w2v_size50_window1_results_extracted.txt
python3 src/util/extract.py src/english/vectors/svm/w2v_size50_window2_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" > src/english/vectors/svm/w2v_size50_window2_results_extracted.txt
python3 src/util/extract.py src/english/vectors/svm/w2v_size50_window3_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" > src/english/vectors/svm/w2v_size50_window3_results_extracted.txt
python3 src/util/extract.py src/english/vectors/svm/w2v_size50_window4_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" > src/english/vectors/svm/w2v_size50_window4_results_extracted.txt
python3 src/util/extract.py src/english/vectors/svm/w2v_size50_window5_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" > src/english/vectors/svm/w2v_size50_window5_results_extracted.txt
python3 src/util/extract.py src/english/vectors/svm/w2v_size100_window1_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" > src/english/vectors/svm/w2v_size100_window1_results_extracted.txt
python3 src/util/extract.py src/english/vectors/svm/w2v_size100_window2_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" > src/english/vectors/svm/w2v_size100_window2_results_extracted.txt
python3 src/util/extract.py src/english/vectors/svm/w2v_size100_window3_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" > src/english/vectors/svm/w2v_size100_window3_results_extracted.txt
python3 src/util/extract.py src/english/vectors/svm/w2v_size100_window4_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" > src/english/vectors/svm/w2v_size100_window4_results_extracted.txt
python3 src/util/extract.py src/english/vectors/svm/w2v_size100_window5_results.txt "['AddToPlaylist', 'BookRestaurant', 'GetWeather', 'PlayMusic', 'RateBook', 'SearchCreativeWork', 'SearchScreeningEvent']" > src/english/vectors/svm/w2v_size100_window5_results_extracted.txt
# END BLOCK
# END ENGLISH


# -------- PORTUGUESE --------
# Logistic Regression - ngrams features
python3 src/util/extract.py src/portuguese/ngrams/logisticregression/unigrams_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" > src/portuguese/ngrams/logisticregression/unigrams_results_extracted.txt
python3 src/util/extract.py src/portuguese/ngrams/logisticregression/bigrams_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" > src/portuguese/ngrams/logisticregression/bigrams_results_extracted.txt
python3 src/util/extract.py src/portuguese/ngrams/logisticregression/trigrams_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" > src/portuguese/ngrams/logisticregression/trigrams_results_extracted.txt

# Naive Bayes - ngrams features
python3 src/util/extract.py src/portuguese/ngrams/naivebayes/BernoulliNB_unigrams_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" > src/portuguese/ngrams/naivebayes/BernoulliNB_unigrams_results_extracted.txt
python3 src/util/extract.py src/portuguese/ngrams/naivebayes/BernoulliNB_bigrams_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" > src/portuguese/ngrams/naivebayes/BernoulliNB_bigrams_results_extracted.txt
python3 src/util/extract.py src/portuguese/ngrams/naivebayes/BernoulliNB_trigrams_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" > src/portuguese/ngrams/naivebayes/BernoulliNB_trigrams_results_extracted.txt

python3 src/util/extract.py src/portuguese/ngrams/naivebayes/GaussianNB_unigrams_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" > src/portuguese/ngrams/naivebayes/GaussianNB_unigrams_results_extracted.txt
python3 src/util/extract.py src/portuguese/ngrams/naivebayes/GaussianNB_bigrams_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" > src/portuguese/ngrams/naivebayes/GaussianNB_bigrams_results_extracted.txt
python3 src/util/extract.py src/portuguese/ngrams/naivebayes/GaussianNB_trigrams_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" > src/portuguese/ngrams/naivebayes/GaussianNB_trigrams_results_extracted.txt

python3 src/util/extract.py src/portuguese/ngrams/naivebayes/MultinomialNB_unigrams_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" > src/portuguese/ngrams/naivebayes/MultinomialNB_unigrams_results_extracted.txt
python3 src/util/extract.py src/portuguese/ngrams/naivebayes/MultinomialNB_bigrams_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" > src/portuguese/ngrams/naivebayes/MultinomialNB_bigrams_results_extracted.txt
python3 src/util/extract.py src/portuguese/ngrams/naivebayes/MultinomialNB_trigrams_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" > src/portuguese/ngrams/naivebayes/MultinomialNB_trigrams_results_extracted.txt
# END BLOCK

# Perceptron - vectors features
python3 src/util/extract.py src/portuguese/vectors/neuralnetwork/w2v_size25_window1_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" > src/portuguese/vectors/neuralnetwork/w2v_size25_window1_results_extracted.txt
python3 src/util/extract.py src/portuguese/vectors/neuralnetwork/w2v_size25_window2_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" > src/portuguese/vectors/neuralnetwork/w2v_size25_window2_results_extracted.txt
python3 src/util/extract.py src/portuguese/vectors/neuralnetwork/w2v_size25_window3_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" > src/portuguese/vectors/neuralnetwork/w2v_size25_window3_results_extracted.txt
python3 src/util/extract.py src/portuguese/vectors/neuralnetwork/w2v_size25_window4_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" > src/portuguese/vectors/neuralnetwork/w2v_size25_window4_results_extracted.txt
python3 src/util/extract.py src/portuguese/vectors/neuralnetwork/w2v_size25_window5_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" > src/portuguese/vectors/neuralnetwork/w2v_size25_window5_results_extracted.txt
python3 src/util/extract.py src/portuguese/vectors/neuralnetwork/w2v_size50_window1_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" > src/portuguese/vectors/neuralnetwork/w2v_size50_window1_results_extracted.txt
python3 src/util/extract.py src/portuguese/vectors/neuralnetwork/w2v_size50_window2_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" > src/portuguese/vectors/neuralnetwork/w2v_size50_window2_results_extracted.txt
python3 src/util/extract.py src/portuguese/vectors/neuralnetwork/w2v_size50_window3_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" > src/portuguese/vectors/neuralnetwork/w2v_size50_window3_results_extracted.txt
python3 src/util/extract.py src/portuguese/vectors/neuralnetwork/w2v_size50_window4_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" > src/portuguese/vectors/neuralnetwork/w2v_size50_window4_results_extracted.txt
python3 src/util/extract.py src/portuguese/vectors/neuralnetwork/w2v_size50_window5_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" > src/portuguese/vectors/neuralnetwork/w2v_size50_window5_results_extracted.txt
python3 src/util/extract.py src/portuguese/vectors/neuralnetwork/w2v_size100_window1_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" > src/portuguese/vectors/neuralnetwork/w2v_size100_window1_results_extracted.txt
python3 src/util/extract.py src/portuguese/vectors/neuralnetwork/w2v_size100_window2_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" > src/portuguese/vectors/neuralnetwork/w2v_size100_window2_results_extracted.txt
python3 src/util/extract.py src/portuguese/vectors/neuralnetwork/w2v_size100_window3_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" > src/portuguese/vectors/neuralnetwork/w2v_size100_window3_results_extracted.txt
python3 src/util/extract.py src/portuguese/vectors/neuralnetwork/w2v_size100_window4_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" > src/portuguese/vectors/neuralnetwork/w2v_size100_window4_results_extracted.txt
python3 src/util/extract.py src/portuguese/vectors/neuralnetwork/w2v_size100_window5_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" > src/portuguese/vectors/neuralnetwork/w2v_size100_window5_results_extracted.txt

# Support Vector Machine - vectors features
python3 src/util/extract.py src/portuguese/vectors/svm/w2v_size25_window1_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" > src/portuguese/vectors/svm/w2v_size25_window1_results_extracted.txt
python3 src/util/extract.py src/portuguese/vectors/svm/w2v_size25_window2_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" > src/portuguese/vectors/svm/w2v_size25_window2_results_extracted.txt
python3 src/util/extract.py src/portuguese/vectors/svm/w2v_size25_window3_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" > src/portuguese/vectors/svm/w2v_size25_window3_results_extracted.txt
python3 src/util/extract.py src/portuguese/vectors/svm/w2v_size25_window4_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" > src/portuguese/vectors/svm/w2v_size25_window4_results_extracted.txt
python3 src/util/extract.py src/portuguese/vectors/svm/w2v_size25_window5_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" > src/portuguese/vectors/svm/w2v_size25_window5_results_extracted.txt
python3 src/util/extract.py src/portuguese/vectors/svm/w2v_size50_window1_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" > src/portuguese/vectors/svm/w2v_size50_window1_results_extracted.txt
python3 src/util/extract.py src/portuguese/vectors/svm/w2v_size50_window2_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" > src/portuguese/vectors/svm/w2v_size50_window2_results_extracted.txt
python3 src/util/extract.py src/portuguese/vectors/svm/w2v_size50_window3_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" > src/portuguese/vectors/svm/w2v_size50_window3_results_extracted.txt
python3 src/util/extract.py src/portuguese/vectors/svm/w2v_size50_window4_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" > src/portuguese/vectors/svm/w2v_size50_window4_results_extracted.txt
python3 src/util/extract.py src/portuguese/vectors/svm/w2v_size50_window5_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" > src/portuguese/vectors/svm/w2v_size50_window5_results_extracted.txt
python3 src/util/extract.py src/portuguese/vectors/svm/w2v_size100_window1_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" > src/portuguese/vectors/svm/w2v_size100_window1_results_extracted.txt
python3 src/util/extract.py src/portuguese/vectors/svm/w2v_size100_window2_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" > src/portuguese/vectors/svm/w2v_size100_window2_results_extracted.txt
python3 src/util/extract.py src/portuguese/vectors/svm/w2v_size100_window3_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" > src/portuguese/vectors/svm/w2v_size100_window3_results_extracted.txt
python3 src/util/extract.py src/portuguese/vectors/svm/w2v_size100_window4_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" > src/portuguese/vectors/svm/w2v_size100_window4_results_extracted.txt
python3 src/util/extract.py src/portuguese/vectors/svm/w2v_size100_window5_results.txt "['add', 'bad', 'bye', 'cancel', 'delete', 'get', 'greeting', 'help', 'ok', 'saymyname', 'thanks', 'welcome']" > src/portuguese/vectors/svm/w2v_size100_window5_results_extracted.txt
# END BLOCK
# END PORTUGUESE
